/**
 * DO NOT EDIT BY HAND — generated by `scripts/build-themes.mjs`.
 *
 * Re-run:  bun scripts/build-themes.mjs
 *
 * PROVENANCE AND LICENCE. The palettes below are extracted verbatim from
 * OpenChamber's compiled theme registry (github.com/openchamber/openchamber),
 * which is MIT licensed — Copyright (c) 2025 Bohdan Triapitsyn. MIT permits
 * reuse and redistribution provided the notice is retained, which is why this
 * banner and `docs/2026-10-03-theme-system.md` both carry it. Several palettes
 * credit their own upstream author on the `author` field; those credits are kept
 * so a future licence change has the provenance it would need.
 *
 * Field presence is deliberately uneven, because upstream is uneven:
 *
 *   surface.elevatedForeground  absent from all 20 palettes
 *   primary.foreground          absent from 5
 *   status.errorForeground      absent from 6
 *   surface.subtle              absent from 6
 *
 * `theme-css.ts` derives every absent value from colours the palette does
 * provide, which is why no placeholder hexes appear below.
 */

/** A palette in the subset TBAi maps onto its own tokens. Missing keys are derived. */
export interface ThemePalette {
  primary?: {
    base?: string;
    foreground?: string;
    hover?: string;
    active?: string;
    muted?: string;
  };
  surface?: {
    background?: string;
    foreground?: string;
    muted?: string;
    mutedForeground?: string;
    elevated?: string;
    elevatedForeground?: string;
    overlay?: string;
    subtle?: string;
  };
  interactive?: {
    border?: string;
    borderHover?: string;
    selection?: string;
    selectionForeground?: string;
    hover?: string;
    active?: string;
    focusRing?: string;
  };
  status?: {
    error?: string;
    errorForeground?: string;
    warning?: string;
    warningForeground?: string;
    success?: string;
    successForeground?: string;
  };
  markdown?: {
    link?: string;
    linkHover?: string;
  };
}

export type ThemeVariant = "light" | "dark";

export interface ThemeDefinition {
  /** Stable family id. Also the `data-tbai-theme` attribute value. */
  readonly id: string;
  /** Name shown in the picker. */
  readonly name: string;
  /** Upstream author of the palette, as credited by OpenChamber. */
  readonly author: string | null;
  /**
   * True only for `classic`. Its colours ship in `globals.css` as `:root`/`.dark`,
   * so no block is generated for it — that is what keeps TBAi's current look the
   * default rather than a re-derivation of itself.
   */
  readonly builtin: boolean;
  readonly light: ThemePalette;
  readonly dark: ThemePalette;
}

const CLASSIC_LIGHT: ThemePalette = {
    primary: {
      base: "#18181b",
      foreground: "#fafafa",
    },
    surface: {
      background: "#ffffff",
      foreground: "#09090b",
      muted: "#f4f4f5",
      mutedForeground: "#71717a",
      elevated: "#ffffff",
      subtle: "#f4f4f5",
    },
    interactive: {
      border: "#e4e4e7",
      selection: "#f4f4f5",
      focusRing: "#a1a1aa",
    },
    status: {
      error: "#ef4444",
      errorForeground: "#fafafa",
      warning: "#d97706",
      warningForeground: "#fafafa",
      success: "#16a34a",
      successForeground: "#fafafa",
    },
  };

const CLASSIC_DARK: ThemePalette = {
    primary: {
      base: "oklch(0.87 0 0)",
      foreground: "oklch(0.205 0 0)",
    },
    surface: {
      background: "#0a0a0a",
      foreground: "oklch(0.985 0 0)",
      muted: "oklch(0.269 0 0)",
      mutedForeground: "oklch(0.708 0 0)",
      elevated: "oklch(0.205 0 0)",
      subtle: "oklch(0.371 0 0)",
    },
    interactive: {
      border: "oklch(1 0 0 / 10%)",
      selection: "oklch(0.371 0 0)",
      focusRing: "oklch(0.556 0 0)",
    },
    status: {
      error: "oklch(0.704 0.191 22.216)",
      errorForeground: "#fafafa",
      warning: "#fbbf24",
      warningForeground: "#0a0a0a",
      success: "#4ade80",
      successForeground: "#0a0a0a",
    },
  };

/** The theme used when nothing is stored, and what a reset returns to. */
export const DEFAULT_THEME_ID = "classic";

/** Every selectable theme. `classic` is first because it is the default. */
export const THEMES: readonly ThemeDefinition[] = [
  {
    id: "classic",
    name: "Classic",
    author: null,
    builtin: true,
    light: CLASSIC_LIGHT,
    dark: CLASSIC_DARK,
  },

  {
    id: "aura",
    name: "Aura",
    author: null,
    builtin: false,
    light: {
      primary: {
        base: "#A277FF",
        foreground: "#F5F0FF",
        hover: "#B38FFF",
        active: "#8D68DD",
        muted: "#A277FF80",
      },
      surface: {
        background: "#F5F0FF",
        foreground: "#2D2640",
        muted: "#EFE8FC",
        mutedForeground: "#807b8b",
        elevated: "#f1ebfb",
        overlay: "#15101F20",
      },
      interactive: {
        border: "#E0D6F2",
        borderHover: "#D5C9EB",
        selection: "#bdb2d74c",
        selectionForeground: "#15101F",
        hover: "#bdb2d72d",
        active: "#bdb2d74c",
        focusRing: "#A277FF40",
      },
      status: {
        error: "#D94F4F",
        errorForeground: "#F5F0FF",
        warning: "#D9A24A",
        warningForeground: "#F5F0FF",
        success: "#40BF7A",
        successForeground: "#F5F0FF",
      },
      markdown: {
        link: "#A277FF",
        linkHover: "#C17AC8",
      },
    },
    dark: {
      primary: {
        base: "#A277FF",
        foreground: "#15141B",
        hover: "#8D68DD",
        active: "#B08BFF",
        muted: "#A277FF80",
      },
      surface: {
        background: "#15141B",
        foreground: "#C8C4D0",
        muted: "#1A1921",
        mutedForeground: "#8a8282",
        elevated: "#201e2b",
        overlay: "#FFFFFF20",
        subtle: "#25232f",
      },
      interactive: {
        border: "#2a2935",
        borderHover: "#47415a",
        selection: "#95abe02d",
        selectionForeground: "#FFFFFF",
        hover: "#7887ac2d",
        active: "#95abe02d",
        focusRing: "#A277FF40",
      },
      status: {
        error: "#FF6767",
        errorForeground: "#15141B",
        warning: "#FFCA85",
        warningForeground: "#15141B",
        success: "#61FFCA",
        successForeground: "#15141B",
      },
      markdown: {
        link: "#A277FF",
        linkHover: "#F694FF",
      },
    },
  },

  {
    id: "ayu",
    name: "Ayu",
    author: null,
    builtin: false,
    light: {
      primary: {
        base: "#4AA8C8",
        foreground: "#FDFAF4",
        hover: "#6EB8D1",
        active: "#4394B0",
        muted: "#4AA8C880",
      },
      surface: {
        background: "#FDFAF4",
        foreground: "#394049",
        muted: "#f7f3eb",
        mutedForeground: "#777e87",
        elevated: "#faf6ed",
        elevatedForeground: "#4F5964",
        overlay: "#1B232B20",
        subtle: "#FFF7E5",
      },
      interactive: {
        border: "#ece5d9",
        borderHover: "#DCD3C5",
        selection: "#9fb2c43e",
        selectionForeground: "#171e25",
        hover: "#9fb2c42c",
        active: "#9fb2c43e",
        focusRing: "#4AA8C840",
      },
      status: {
        error: "#E6656A",
        errorForeground: "#FDFAF4",
        warning: "#EA9F41",
        warningForeground: "#FDFAF4",
        success: "#5FB978",
        successForeground: "#FDFAF4",
      },
      markdown: {
        link: "#2F9BCE",
        linkHover: "#4AA8C8",
      },
    },
    dark: {
      primary: {
        base: "#3FB7E3",
        foreground: "#0F1419",
        hover: "#389FC5",
        active: "#5BC1E7",
        muted: "#3FB7E380",
      },
      surface: {
        background: "#0F1419",
        foreground: "#D6DAE0",
        muted: "#18222C",
        mutedForeground: "#777e86",
        elevated: "#17202a",
        overlay: "#FBFBFD20",
        subtle: "#1e252d",
      },
      interactive: {
        border: "#292c30",
        borderHover: "#323C49",
        selection: "#c7c7df1d",
        selectionForeground: "#FBFBFD",
        hover: "#b6b6cc1d",
        active: "#b8b8ce1d",
        focusRing: "#3FB7E340",
      },
      status: {
        error: "#F58572",
        errorForeground: "#0F1419",
        warning: "#E4A75C",
        warningForeground: "#0F1419",
        success: "#78D05C",
        successForeground: "#0F1419",
      },
      markdown: {
        link: "#66C6F1",
        linkHover: "#3FB7E3",
      },
    },
  },

  {
    id: "carbonfox",
    name: "Carbonfox",
    author: null,
    builtin: false,
    light: {
      primary: {
        base: "#0072C3",
        hover: "#338ECF",
        active: "#0061A6",
        muted: "#0072C380",
      },
      surface: {
        background: "#FFFFFF",
        foreground: "#161616",
        muted: "#F4F4F4",
        mutedForeground: "#868585",
        elevated: "#f4f4f7",
        overlay: "#00000020",
        subtle: "#f6f6f8",
      },
      interactive: {
        border: "#e3e2e2",
        borderHover: "#D0D0D0",
        selection: "#cacfd87f",
        selectionForeground: "#000000",
        hover: "#43424214",
        active: "#43424212",
        focusRing: "#0F62FE40",
      },
      status: {
        error: "#DA1E28",
        warning: "#F1C21B",
        warningForeground: "#FFFFFF",
        success: "#198038",
      },
      markdown: {
        link: "#0072C3",
        linkHover: "#0043CE",
      },
    },
    dark: {
      primary: {
        base: "#33B1FF",
        foreground: "#161616",
        hover: "#2F9ADC",
        active: "#52BDFF",
        muted: "#33B1FF80",
      },
      surface: {
        background: "#161616",
        foreground: "#CACDD1",
        muted: "#222222",
        mutedForeground: "#8b8a8a",
        elevated: "#222222",
        overlay: "#FFFFFF20",
        subtle: "#292828",
      },
      interactive: {
        border: "#2d2c2c",
        borderHover: "#4C4C4C",
        selection: "#ffffff20",
        selectionForeground: "#FFFFFF",
        hover: "#ffffff12",
        active: "#ffffff12",
        focusRing: "#4589FF40",
      },
      status: {
        error: "#FF8389",
        errorForeground: "#161616",
        warning: "#F1C21B",
        warningForeground: "#161616",
        success: "#42BE65",
        successForeground: "#161616",
      },
      markdown: {
        link: "#33B1FF",
        linkHover: "#78A9FF",
      },
    },
  },

  {
    id: "catppuccin",
    name: "Catppuccin",
    author: null,
    builtin: false,
    light: {
      primary: {
        base: "#7130c7",
        hover: "#6e32bf",
        active: "#6b35b8",
        muted: "#7130c780",
      },
      surface: {
        background: "#eff1f5",
        foreground: "#4c4f69",
        muted: "#e6e9ef",
        mutedForeground: "#5c5f77",
        elevated: "#e6e9ef",
        overlay: "#39393420",
      },
      interactive: {
        border: "#66677026",
        borderHover: "#66677026",
        selection: "#ccd0da",
        hover: "#ccd0da80",
        active: "#dbdee4",
        focusRing: "#8839ef",
      },
      status: {
        error: "#d20f39",
        warning: "#fe640b",
        success: "#40a02b",
      },
      markdown: {
        link: "#1e66f5",
        linkHover: "#04a5e5",
      },
    },
    dark: {
      primary: {
        base: "#cba6f7",
        foreground: "#11111b",
        hover: "#dec7fa",
        active: "#dec7fa",
        muted: "#cba6f780",
      },
      surface: {
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        muted: "#181825",
        mutedForeground: "#a6adc8",
        elevated: "#181825",
      },
      interactive: {
        border: "#8587961d",
        borderHover: "#8587961d",
        selection: "#313244",
        hover: "#31324480",
        active: "#333446",
        focusRing: "#cba6f7",
      },
      status: {
        error: "#f38ba8",
        warning: "#fab387",
        success: "#a6e3a1",
      },
      markdown: {
        link: "#89b4fa",
        linkHover: "#89dceb",
      },
    },
  },

  {
    id: "cursor",
    name: "Cursor",
    author: "cedricverlinden",
    builtin: false,
    light: {
      primary: {
        base: "#2567A8",
        foreground: "#FFFFFF",
        hover: "#1D568E",
        active: "#194B7C",
        muted: "#2567A880",
      },
      surface: {
        background: "#FCFCFC",
        foreground: "#30343A",
        muted: "#F6F6F6",
        mutedForeground: "#60656B",
        elevated: "#F1F1F1",
      },
      interactive: {
        border: "#50586026",
        borderHover: "#50586040",
        selection: "#E1E1E1",
        selectionForeground: "#253C52",
        hover: "#0000000A",
        active: "#00000014",
        focusRing: "#2567A8B3",
      },
      status: {
        error: "#A3424B",
        warning: "#806015",
        success: "#467037",
      },
      markdown: {
        link: "#2567A8",
        linkHover: "#1D568E",
      },
    },
    dark: {
      primary: {
        base: "#4c9df3",
        foreground: "#191c22",
        hover: "#66aefa",
        active: "#66aefa",
        muted: "#4c9df380",
      },
      surface: {
        background: "#1a1a1a",
        foreground: "#CCCCCCdd",
        muted: "#141414",
        mutedForeground: "#848484",
        elevated: "#141414",
      },
      interactive: {
        border: "#8484841f",
        borderHover: "#8484841f",
        selection: "#ffffff1d",
        selectionForeground: "#FFFFFF",
        hover: "#2A2A2A99",
        active: "#2d2d2d",
        focusRing: "#4c9df399",
      },
      status: {
        error: "#BF616A",
        warning: "#EBCB8B",
        success: "#A3BE8C",
      },
      markdown: {
        link: "#4c9df3",
        linkHover: "#4c9df3",
      },
    },
  },

  {
    id: "fields-of-the-shire",
    name: "Fields of the Shire",
    author: "OpenChamber",
    builtin: false,
    light: {
      primary: {
        base: "#4a6030",
        foreground: "#faf8f5",
        hover: "#5e773f",
        active: "#708a50",
        muted: "#4a603080",
      },
      surface: {
        background: "#f9f5eb",
        foreground: "#1a1612",
        muted: "#f4efe3",
        mutedForeground: "#5a5048",
        elevated: "#fcf9f0",
        overlay: "#1a161220",
        subtle: "#f1ece1",
      },
      interactive: {
        border: "#1a16121c",
        borderHover: "#1a161230",
        selection: "#1a16121a",
        hover: "#efe8da",
        focusRing: "#4a603040",
      },
      status: {
        error: "#a24d3f",
        errorForeground: "#faf8f5",
        warning: "#8c5520",
        warningForeground: "#faf8f5",
        success: "#4a6030",
        successForeground: "#faf8f5",
      },
      markdown: {
        link: "#3d4f5a",
        linkHover: "#4a6030",
      },
    },
    dark: {
      primary: {
        base: "#7a8a5a",
        foreground: "#0c0a08",
        hover: "#93a56b",
        active: "#a4b67d",
        muted: "#7a8a5a80",
      },
      surface: {
        background: "#1b1815",
        foreground: "#ebe0d1",
        muted: "#23201c",
        mutedForeground: "#83796f",
        elevated: "#2b2622",
        overlay: "#1b1815cc",
        subtle: "#282320",
      },
      interactive: {
        border: "#2E2B28",
        borderHover: "#f0e6d830",
        selection: "#f0e6d81f",
        hover: "#332d28",
        active: "#f0e6d824",
        focusRing: "#7a8a5a4d",
      },
      status: {
        error: "#b34d3b",
        errorForeground: "#0c0a08",
        warning: "#c47a3a",
        warningForeground: "#0c0a08",
        success: "#7f905e",
        successForeground: "#0c0a08",
      },
      markdown: {
        link: "#5a6d7a",
        linkHover: "#93a56b",
      },
    },
  },

  {
    id: "gruvbox",
    name: "Gruvbox",
    author: null,
    builtin: false,
    light: {
      primary: {
        base: "#076678",
        foreground: "#FBF1C7",
        hover: "#388288",
        active: "#0C5D6C",
        muted: "#07667880",
      },
      surface: {
        background: "#f8f1d5",
        foreground: "#3C3836",
        muted: "#F2E5BC",
        mutedForeground: "#7C6F64",
        elevated: "#efebcd",
        overlay: "#28282820",
        subtle: "#f3efde",
      },
      interactive: {
        border: "#e8d7b7",
        borderHover: "#C9B897",
        selection: "#f1eaeaec",
        selectionForeground: "#282828",
        hover: "#fffdfdb3",
        active: "#f1eaeaec",
        focusRing: "#07667840",
      },
      status: {
        error: "#9D0006",
        errorForeground: "#FBF1C7",
        warning: "#B57614",
        warningForeground: "#FBF1C7",
        success: "#79740E",
        successForeground: "#FBF1C7",
      },
      markdown: {
        link: "#427B58",
        linkHover: "#076678",
      },
    },
    dark: {
      primary: {
        base: "#83A598",
        foreground: "#282828",
        hover: "#759287",
        active: "#95B09F",
        muted: "#83A59880",
      },
      surface: {
        background: "#282828",
        foreground: "#EBDBB2",
        muted: "#32302F",
        mutedForeground: "#918574",
        elevated: "#25292b",
        overlay: "#FBF1C720",
        subtle: "#343230",
      },
      interactive: {
        border: "#383430",
        borderHover: "#5A524B",
        selection: "#5a5647db",
        selectionForeground: "#FBF1C7",
        hover: "#5a5647d9",
        active: "#5a5647ec",
        focusRing: "#83A59840",
      },
      status: {
        error: "#FB4934",
        errorForeground: "#282828",
        warning: "#FABD2F",
        warningForeground: "#282828",
        success: "#B8BB26",
        successForeground: "#282828",
      },
      markdown: {
        link: "#8EC07C",
        linkHover: "#83A598",
      },
    },
  },

  {
    id: "jetbrains",
    name: "JetBrains",
    author: "Artem Evsevev, adapted for OpenChamber",
    builtin: false,
    light: {
      primary: {
        base: "#195ce3",
        hover: "#2D61F0",
        active: "#0055FF",
        muted: "#3573F080",
      },
      surface: {
        background: "#FFF",
        foreground: "#000000",
        muted: "#F7F8FA",
        mutedForeground: "#404040",
        elevated: "#FFFFFF",
        overlay: "#00000025",
        subtle: "#f5f8fd",
      },
      interactive: {
        border: "#dde0ea",
        borderHover: "#AEB3C2",
        selection: "#DFE1E5",
        hover: "#E6E6E8",
        active: "#DBDCDE",
        focusRing: "#0055FF40",
      },
      status: {
        error: "#CE0606",
        warning: "#F49810",
        success: "#077D18",
      },
      markdown: {
        link: "#006DCC",
        linkHover: "#3573F0",
      },
    },
    dark: {
      primary: {
        base: "#6796f5",
        foreground: "#1E1F22",
        hover: "#70AEFF",
        active: "#5594FA",
        muted: "#6796f580",
      },
      surface: {
        background: "#1E1F22",
        foreground: "#DFE1E5",
        muted: "#26282B",
        mutedForeground: "#9fa0a2",
        elevated: "#2B2D30",
        overlay: "#00000080",
        subtle: "#28292c",
      },
      interactive: {
        border: "#303238",
        borderHover: "#4B5059",
        selection: "#43454A",
        hover: "#3C3E41",
        active: "#494A4D",
        focusRing: "#6796f550",
      },
      status: {
        error: "#FA6675",
        errorForeground: "#1E1F22",
        warning: "#F2C55C",
        warningForeground: "#1E1F22",
        success: "#57965D",
        successForeground: "#1E1F22",
      },
      markdown: {
        link: "#56A8F5",
        linkHover: "#6796f5",
      },
    },
  },

  {
    id: "openchamber",
    name: "OpenChamber",
    author: "OpenChamber",
    builtin: false,
    light: {
      primary: {
        base: "#b35017",
        hover: "#9a4310",
        active: "#85390c",
        muted: "#b3501780",
      },
      surface: {
        background: "#fdfcfa",
        foreground: "#393a34",
        muted: "#f7f6f4",
        mutedForeground: "#5c5c54",
        elevated: "#f8f7f5",
        overlay: "#39393420",
      },
      interactive: {
        border: "#e5e1de",
        borderHover: "#cbc7c2",
        selection: "#a9998f2b",
        hover: "#0000000d",
        active: "#00000014",
        focusRing: "#b3501755",
      },
      status: {
        error: "#b7493f",
        warning: "#8d6c15",
        success: "#5f8d3d",
        successForeground: "#ffffff",
      },
      markdown: {
        link: "#2e808f",
        linkHover: "#296aa3",
      },
    },
    dark: {
      primary: {
        base: "#da7c47",
        hover: "#eb8c57",
        active: "#fd9b66",
        muted: "#da7c4780",
      },
      surface: {
        background: "#120f0e",
        foreground: "#c9c5ba",
        muted: "#171615",
        mutedForeground: "#8f8b81",
        elevated: "#181715",
        subtle: "#171616",
      },
      interactive: {
        border: "#242323",
        borderHover: "#504e4c",
        selection: "#c8c6c52b",
        hover: "#ffffff12",
        active: "#ffffff1f",
        focusRing: "#da7c4755",
      },
      status: {
        error: "#da5b4a",
        warning: "#c67f13",
        success: "#76ad4f",
      },
      markdown: {
        link: "#5d99a9",
        linkHover: "#6ba7b8",
      },
    },
  },

  {
    id: "vesper",
    name: "Vesper",
    author: null,
    builtin: false,
    light: {
      primary: {
        base: "#a06535",
        hover: "#FFD2AD",
        active: "#D9A982",
        muted: "#cf9c7280",
      },
      surface: {
        background: "#FFFFFF",
        foreground: "#101010",
        muted: "#F8F8F8",
        mutedForeground: "#6e6d6d",
        elevated: "#f6f5f5",
        overlay: "#00000020",
        subtle: "#f6f2f2",
      },
      interactive: {
        border: "#E9E5E5",
        borderHover: "#E0E0E0",
        selection: "#5e5b5b22",
        selectionForeground: "#000000",
        hover: "#5e5c5c22",
        active: "#48474722",
        focusRing: "#cf9c7240",
      },
      status: {
        error: "#d46868",
        errorForeground: "#FFFFFF",
        warning: "#cb7f40",
        warningForeground: "#FFFFFF",
        success: "#109b76",
        successForeground: "#FFFFFF",
      },
      markdown: {
        link: "#717070",
        linkHover: "#c48959",
      },
    },
    dark: {
      primary: {
        base: "#FFC799",
        foreground: "#101010",
        hover: "#DBAC84",
        active: "#FFCFA8",
        muted: "#FFC79980",
      },
      surface: {
        background: "#151515",
        foreground: "#e8e5e5",
        muted: "#1c1b1b",
        mutedForeground: "#848484",
        elevated: "#242121",
        elevatedForeground: "#FFFFFF",
        overlay: "#FFFFFF20",
        subtle: "#1f1f1f",
      },
      interactive: {
        border: "#2C2B2B",
        borderHover: "#202020",
        selection: "#b1adad33",
        selectionForeground: "#FFFFFF",
        hover: "#ffffff1c",
        active: "#ffffff33",
        focusRing: "#FFC79940",
      },
      status: {
        error: "#FF8080",
        errorForeground: "#101010",
        warning: "#FFC799",
        warningForeground: "#101010",
        success: "#99FFE4",
        successForeground: "#101010",
      },
      markdown: {
        link: "#A0A0A0",
        linkHover: "#FFC799",
      },
    },
  },
] as const;

const BY_ID = new Map<string, ThemeDefinition>(THEMES.map((theme) => [theme.id, theme]));

export function getTheme(id: string): ThemeDefinition | undefined {
  return BY_ID.get(id);
}

export function isThemeId(id: unknown): id is string {
  return typeof id === "string" && BY_ID.has(id);
}
