/**
 * Single source of truth for scheduler page copy (toolbar, list, detail,
 * gallery, editor, timeline, confirms). Components reference this — no
 * literals live in the scheduler feature.
 */
export const schedulerViewConfig = {
  copy: {
    toolbarAll: "All",
    toolbarEnabled: "Enabled",
    toolbarDisabled: "Disabled",
    newJob: "New Job",
    blankTitle: "Blank job",
    blankDesc: "Start from scratch with a one-time run",
    startFromTemplate: "Start from a template",
    cancel: "Cancel",
    backToList: "Back to jobs",
    backToTemplates: "Back to templates",
    noJobs: "No scheduled jobs yet.",
    noJobsHint: "Create your first job to automate a run.",
    noMatches: "No jobs match this filter.",
    selectHint: "Select a job to see details.",
    runNow: "Run now",
    enable: "Enable",
    disable: "Disable",
    edit: "Edit",
    duplicate: "Duplicate",
    delete: "Delete",
    deleteTitle: "Delete job?",
    deleteDescription: (name: string) =>
      `“${name}” and its run history will be permanently deleted. This cannot be undone.`,
    moreActions: "More actions",
    factsSchedule: "Schedule",
    factsNextRun: "Next run",
    factsLastRun: "Last run",
    factsAi: "AI",
    factsWorkspace: "Workspace",
    factsConversation: "Conversation",
    factsDedicatedThread: "New dedicated chat",
    factsExistingThread: "Existing chat",
    openThread: "Open thread",
    historyTitle: "Run history",
    historyEmpty: "No runs yet.",
    historyRefresh: "Refresh history",
    runAttempt: (n: number) => `Attempt ${n}`,
    runOutput: "Output",
    runError: "Error",
    runManual: "Manual run",
    runScheduled: "Scheduled run",
    cancelRun: "Cancel run",
    disabledSuffix: "disabled",
    editorNewTitle: "New job",
    editorEditTitle: "Edit job",
    editorSave: "Save job",
    editorSaving: "Saving…",
    markSeen: "Mark seen",
    unseenFailures: (n: number) =>
      `${n} unseen failure${n === 1 ? "" : "s"}`,
    dismissError: "Dismiss error",
    runStarted: (name: string) => `Run started: ${name}`,
    repeatMinutes: "Every few minutes",
    repeatHourly: "Hourly",
    repeatDaily: "Daily",
    repeatWeekdays: "Weekdays",
    repeatWeekly: "Weekly",
    repeatMonthly: "Monthly",
    repeatAdvanced: "Custom schedule",
    repeatOnce: "One time",
    patternList: [
      ["*/5 * * * *", "Every 5 min"],
      ["*/15 * * * *", "Every 15 min"],
      ["0 9 * * MON-FRI", "Weekdays 9:00"],
      ["0,30 9-17 * * *", "Business hrs"],
      ["@daily", "@daily"],
      ["@weekly", "@weekly"],
      ["@monthly", "@monthly"],
    ] as Array<[string, string]>,
    editor: {
      general: "General",
      jobNamePlaceholder: "Job name",
      descriptionPlaceholder: "Description (optional)",
      when: "When",
      once: "Once",
      repeat: "Repeat",
      date: "Date",
      time: "Time",
      quickSlot1h: "+1h",
      quickSlotTomorrow: "Tomorrow 9:00",
      quickSlotNextMon: "Next Mon 9:00",
      repeatLabel: "Repeat",
      everyNMinutes: "Every N minutes (1-59)",
      minutesUnit: "min",
      hour: "Hour (0-23)",
      minute: "Minute (0-59)",
      day: "Day",
      monthDay: "Day (1-28)",
      customExpression:
        "Custom expression (minute hour day month weekday — @daily/@weekly/@monthly/@yearly/@hourly also work)",
      cronPlaceholder: "0 9 * * *",
      popularPatterns: "Popular patterns",
      timezone: "Timezone",
      timezonePlaceholder: "Asia/Kolkata",
      pickDateHintOnce: "Pick a date and time to see the schedule.",
      pickDateHintRepeat: "Adjust the repeat settings to see the schedule.",
      runsIn24h: (n: number) => ` · ${n} run(s) in next 24h`,
      ai: "AI",
      provider: "Provider",
      selectProvider: "Select provider…",
      model: "Model",
      selectModel: "Select model…",
      thinking: "Thinking",
      thinkingOff: "Off",
      thinkingLow: "Low",
      thinkingMedium: "Medium",
      thinkingHigh: "High",
      workspace: "Workspace",
      workspacePlaceholder:
        "Absolute folder path inside the TBAi workspace root",
      prompt: "Prompt",
      promptPlaceholder: "What should the scheduled run do?",
      conversation: "Conversation",
      newDedicated: "New dedicated chat",
      newDedicatedHint: "(auto-create and reuse)",
      existingChat: "Existing chat",
      selectConversation: "Select conversation",
      selectConversationPlaceholder: "— Select a conversation —",
      execution: "Execution",
      maxRetries: "Max retries (0-10)",
      retryDelay: "Retry delay (s)",
      timeout: "Timeout (s)",
      missedGrace: "Missed grace (s)",
      overlapNote:
        "Overlap: skip if a previous run is still running. Destructive tools always require interactive approval and refuse in scheduled runs.",
      save: "Save",
      create: "Create",
      saving: "Saving…",
      cancel: "Cancel",
      closeForm: "Close form",
      editJobTitle: "Edit Job",
      newJobTitle: "New Job",
      errName: "Name is required",
      errProvider: "Provider is required",
      errModel: "Model is required",
      errWorkspace: "Workspace path is required",
      errPrompt: "Prompt is required",
      errDate: "Date and time are required for a one-time job",
      errDateInvalid: "Invalid date/time",
      errCron: "A cron expression is required",
      errSave: "Save failed",
      errPreview: "Preview failed",
      jobUpdated: "Job updated",
      jobCreated: "Job created",
    },
  },
};
