"use client";

import type { ComponentProps } from "react";
import { Check as CheckIcon, Loader as Loader2Icon, X as XIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { mono, paper } from "./surfaces";
import { take } from "../utils/range";

/**
 * Official assistant-ui Terminal Block element, vendored verbatim from the
 * assistant-ui registry
 * (packages/ui/src/components/react/assistant-ui/elements/terminal-block.tsx)
 * because `npx assistant-ui add terminal-block` cannot resolve in this repo
 * (registry 404s for the element name under every flavor path tried).
 *
 * The ONLY adaptations:
 *  1. `CheckIcon`/`Loader2Icon` do not exist in the installed lucide-react
 *     version, so they are aliased to `Check`/`Loader` here.
 *  2. `status` is destructured from props (upstream declares and documents it
 *     and reads it in the body, but omits it from the destructuring list, so
 *     the body silently read the global `window.status` instead). Without this,
 *     `status === "error"` is never true and a failed command renders a green
 *     "exit 0" badge. One line; no styling, behavior, or API change.
 *
 * No other styling, behavior, or API changes. Do NOT edit this file beyond
 * those — adapt around it in `web/src/tools/computer/terminal-ui.tsx`.
 */
export function TerminalBlock({
  command,
  lines,
  visibleCount,
  done,
  variant = "paper",
  status,
  className,
  ...props
}: Omit<
  ComponentProps<"div">,
  "children" | "command" | "lines" | "visibleCount" | "done" | "variant"
> & {
  command: string;
  lines: readonly string[];
  visibleCount: number;
  done: boolean;
  variant?: "paper" | "ink";
  /**
   * Header status. Defaults to deriving from `done` (success → green "exit 0").
   * Pass "error" to show a red failure badge instead — the TBAi chrome renders
   * the real exit code / timeout below the block.
   */
  status?: "success" | "error";
}) {
  const ink = variant === "ink";

  return (
    <div
      data-slot="terminal-block"
      className={cn(
        ink ? "bg-foreground dark:bg-popover" : paper,
        "w-full max-w-md overflow-hidden rounded-2xl font-mono text-xs",
        className,
      )}

      {...props}
    >
      <div className="flex items-center justify-between px-4 pt-3 pb-1.5">
        <span
          className={cn(
            ink
              ? "text-background/90 dark:text-foreground/90"
              : "text-foreground/90",
          )}
        >
          {command}
        </span>
        {done ? (
          status === "error" ? (
            <div className="flex items-center gap-1">
              <XIcon className="size-3 text-destructive" />
              <span
                className={cn(
                  mono,
                  ink
                    ? "text-background/40 dark:text-foreground/40"
                    : "text-foreground/40",
                )}
              >
                failed
              </span>
            </div>
          ) : (
            <div className="flex items-center gap-1">
              <CheckIcon className="size-3 text-emerald-500" />
              <span
                className={cn(
                  mono,
                  ink
                    ? "text-background/40 dark:text-foreground/40"
                    : "text-foreground/40",
                )}
              >
                exit 0
              </span>
            </div>
          )
        ) : (
          <Loader2Icon
            className={cn(
              "size-3 animate-spin motion-reduce:animate-none",
              ink
                ? "text-background/35 dark:text-foreground/35"
                : "text-foreground/35",
            )}
          />
        )}
      </div>
      <div
        className={cn(
          "flex min-h-[8.5rem] flex-col gap-1 px-4 pt-1 pb-3.5",
          ink
            ? "text-background/55 dark:text-foreground/50"
            : "text-foreground/50",
        )}
      >
        {take(lines, visibleCount).map((line, i) => {
          const isLast = i === lines.length - 1;
          return (
            <div
              key={`${i}-${line}`}
              className={cn(
                "fade-in animate-in fill-mode-both duration-300",
                isLast &&
                  (ink
                    ? "text-background/90 dark:text-foreground/90"
                    : "text-foreground/90"),
              )}
            >
              {line}
            </div>
          );
        })}
        {!done && (
          <span
            aria-hidden
            className="inline-block h-3 w-1.5 animate-pulse bg-blue-500/70 motion-reduce:animate-none dark:bg-blue-400/70"
          />
        )}
      </div>
    </div>
  );
}
